### ISSUE TITLE
Update clap to fix compilation issue

### ISSUE THREAD

**Issue by veprolet** [Tashima42/hash-id-rust#3]
When installing from AUR using the latest stable toolchain (rustc 1.59), the compilation fails for me during the compilation of the `unicode_width 0.1.8` crate (`clap` dependency) with many instances of the following error:
```
error: unknown start of token: \u{0}
```
While this is clearly an upstream error, I wasn't able to find any relevant issues there and the bug is not present in the later versions. I suggest upgrading `clap` to the latest version, as it fixes the issue and requires minimal code changes.

**Comment by tashima42** [comment]
Thank you very much, @veprolet. The issue seems to be fixed and working, I'll make a release later for the snap and deb packages too.
